[versions]
agp = "9.0.0"
kotlin= "2.3.10"
preferenceKtx = "1.2.1"
reviewKtx = "2.0.2"

[libraries]
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "reviewKtx" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
